name: Build Docker Image

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      image_tag:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker SHA Tag
        id: vars
        run: echo "SHA_TAG=${{ inputs.image_tag }}-${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        run: echo "${{ inputs.docker_password }}" | docker login -u "${{ inputs.docker_username }}" --password-stdin

      - name: Tag Docker image for Stage
        run: |
          docker tag my-image:${{ env.SHA_TAG }} ${{ secrets.DOCKER_HUB_USERNAME }}/stage:${{ env.SHA_TAG }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/stage:${{ env.SHA_TAG }}

      - name: Tag Docker image for Production
        run: |
          docker tag my-image:${{ env.SHA_TAG }} ${{ secrets.DOCKER_HUB_USERNAME }}/production:${{ env.SHA_TAG }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/production:${{ env.SHA_TAG }}
