name: Build for Production

on:
  push:
    branches:
      - production
  pull_request:
    types: [closed]
    branches:
      - production

jobs:
  call-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker credentials
        id: docker_creds
        run: |
          echo "::set-env name=DOCKER_USERNAME::${{ secrets.DOCKER_HUB_USERNAME }}"
          echo "::set-env name=DOCKER_PASSWORD::${{ secrets.DOCKER_HUB_PASSWORD }}"

      - name: Call Build Workflow for Production
        uses: ./.github/workflows/docker-image.yml
        with:
          branch: production
          image_tag: ${{ github.sha }}
          docker_username: ${{ steps.docker_creds.outputs.DOCKER_USERNAME }}
          docker_password: ${{ steps.docker_creds.outputs.DOCKER_PASSWORD }}
