name: Build for Production

on:
  push:
    branches:
      - production

jobs:
  build-for-production:
    runs-on: ubuntu-latest

    steps:
    
      - name: Set environment variables for production
        run: |
          echo "REPO_BASE_NAME=manishchauhan27" >> $GITHUB_ENV
          echo "BRANCH_NAME=production" >> $GITHUB_ENV
          echo "REPO_NAME=production" >> $GITHUB_ENV

      - name: Call Build Docker Image Workflow
        run: |
          ./.github/workflows/build-docker-image.yml
