name: Build for Production

on:
  push:
    branches:
      - production

jobs:

  build-for-production:
    uses: ./.github/workflows/build-docker-image.yml
    with:
      repo_base_name: manishchauhan27
      branch_name: production
      repo_name: production
    secrets:
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_hub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}

