name: Build for Production

on:
  push:
    branches:
      - production
  pull_request:
    types: [closed]
    branches:
      - production

jobs:
  call-build:
    runs-on: ubuntu-latest
    steps:
      - name: Call Build Workflow for Production
        uses: ./.github/workflows/build-docker-image.yml
        with:
          branch: production
          docker_username: ${{ secrets.DOCKER_HUB_USERNAME }}
          docker_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
