name: Build for Stage

on:
  push:
    branches:
      - stage

jobs:

  build-for-stage:
    uses: ./.github/workflows/build-docker-image.yml
    with:
      repo_base_name: manishchauhan27
      branch_name: stage
      repo_name: stage
    secrets:
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_hub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}

