name: Build for Stage

on:
  push:
    branches:
      - stage

jobs:
  build-for-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Call Build Docker Image Workflow
        uses: ./.github/workflows/build-docker-image.yml
