name: Build for Stage

on:
  push:
    branches:
      - stage

jobs:
  build-for-stage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set environment variables for stage
        run: |
          echo "REPO_BASE_NAME=manishchauhan27" >> $GITHUB_ENV
          echo "BRANCH_NAME=stage" >> $GITHUB_ENV
          echo "REPO_NAME=stage" >> $GITHUB_ENV

      - name: Call Build Docker Image Workflow
        run: |
          ./.github/workflows/build-docker-image.yml
